
name: .NET Core CI/CD

on:
  push:
    branches: 
      - "main"
      - "develop"
      - "feature/*"
  pull_request:
    branches: 
      - "main"
      - "develop"
      - "feature/*"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:

        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build the solution
      run: dotnet build --no-restore --configuration Release

    - name: Run tests
      run: dotnet test --no-build --configuration Release --verbosity normal

    - name: Upload build artifacts
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: BuildOutput
        path: '**/bin/Release/net*/'

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}

        password: ${{ secrets.DOCKER_TOKEN }}

    # Tilføj trin til at bygge Docker image
    - name: Extract version from .csproj
      id: version
      run: |
        VERSION=$(cat userServiceAPI/userServiceAPI.csproj | grep -oPm1 "(?<=<Version>)[^<]+")
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Build Docker image with version tag
      run: |
        docker build -t mikkelhv/4semuserservice:${{ env.VERSION }} -f ./userServiceAPI/Dockerfile ./userServiceAPI

    - name: Push Docker image to Docker Hub
      run: |
        docker push mikkelhv/4semuserservice:${{ env.VERSION }}
    
    - name: Tag og push docker image med latest versionering
      run: |
        docker tag mikkelhv/4semuserservice:${{ env.VERSION }} mikkelhv/4semuserservice:latest
        docker push mikkelhv/4semuserservice:latest
